/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import Controllers.MainController;
import Controllers.MeetingController;
import Controllers.PurchaseController;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mayra
 */
public class AddPurchase extends javax.swing.JFrame {

    public String meetingId;
    /**
     * Creates new form AddPurchase
     */
    public AddPurchase() {
        initComponents();
        this.meetingId = null;
    }

    public void setMeetingId(String refId){
        this.meetingId = refId;
    }
    
    public void showTable(){
        if (this.meetingId == null){
            jLabel2.setVisible(false);
            txtCost.setVisible(false);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLines = new javax.swing.JTable();
        btnAddLine = new javax.swing.JButton();
        btnDeleteLine = new javax.swing.JButton();
        btnAccept = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        txtCost = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(300, 480));
        setResizable(false);
        setSize(new java.awt.Dimension(300, 480));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/description-icon.png"))); // NOI18N
        jLabel1.setToolTipText("Descripcion");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 80, 90, 40));

        txtDescription.setToolTipText("Descripcion");
        getContentPane().add(txtDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 180, 25));

        tableLines.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Nombre", "Cantidad"
            }
        ));
        jScrollPane1.setViewportView(tableLines);
        if (tableLines.getColumnModel().getColumnCount() > 0) {
            tableLines.getColumnModel().getColumn(0).setResizable(false);
            tableLines.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 220, 130));

        btnAddLine.setText("+");
        btnAddLine.setToolTipText("Agregar");
        btnAddLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLineActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 40, 30));

        btnDeleteLine.setText("-");
        btnDeleteLine.setToolTipText("Quitar");
        btnDeleteLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteLineActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeleteLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 40, 30));

        btnAccept.setText("Aceptar");
        btnAccept.setToolTipText("Aceptar");
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });
        getContentPane().add(btnAccept, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cash.png"))); // NOI18N
        jLabel2.setToolTipText("Monto");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-200, 40, 280, 120));

        btnCancel.setText("Cancelar");
        btnCancel.setToolTipText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, -1, -1));

        txtCost.setToolTipText("Monto");
        getContentPane().add(txtCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 180, 25));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled.png"))); // NOI18N
        jLabel3.setToolTipText("Inicio");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, -20, 160, 100));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white-wallpaper.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 310, 450));

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu-icon.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, -10, 100, 60));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Agregar compra");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 120, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLineActionPerformed
        DefaultTableModel table = (DefaultTableModel) tableLines.getModel();
        table.addRow(new Object[]{"",""});
        
    }//GEN-LAST:event_btnAddLineActionPerformed

    private void btnDeleteLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteLineActionPerformed
        DefaultTableModel table = (DefaultTableModel) tableLines.getModel();
        if(table.getRowCount()>0){
            table.removeRow(table.getRowCount()-1);
        }
    }//GEN-LAST:event_btnDeleteLineActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        MainController mc = MainController.instance();
        mc.getHome().setVisible(true);
        mc.getHome().setLocationRelativeTo(this);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        PurchaseController pc = PurchaseController.instance();
        if (tableLines.getRowCount() > 0){
            String id;
            if (this.meetingId != null){
                id = pc.createMeetingPurchase(meetingId, txtDescription.toString(), Double.parseDouble(txtCost.toString()));
                for (int i = 0; i < tableLines.getRowCount(); i++){
                    String prod = tableLines.getValueAt(i, 0).toString();
                    String cant = tableLines.getValueAt(i, 1).toString();
                    pc.addMeetingPurchaseLine(id, prod, Double.parseDouble(cant));
                }
                MeetingController mc = MeetingController.instance();
                MeetingInformationInterface meetingInfo = new MeetingInformationInterface();
                meetingInfo.setMeeting(mc.getMeeting(meetingId));
                meetingInfo.setVisible(true);
                meetingInfo.setLocationRelativeTo(this);
                dispose();
            }
            else{
                id = pc.createPersonalPurchase(txtDescription.getText(), MainController.instance().getCurrentUser().getUserName());
                for (int i = 0; i < tableLines.getRowCount(); i++){
                    String prod = tableLines.getValueAt(i, 0).toString();
                    String cant = tableLines.getValueAt(i, 1).toString();
                    pc.addPersonalPurchaseLine(id, prod, Double.parseDouble(cant));
                }
                MainController mc = MainController.instance();
                mc.getHome().setVisible(true);
                mc.getHome().setLocationRelativeTo(this);
                dispose();
            }
            this.meetingId = null;
        }
    }//GEN-LAST:event_btnAcceptActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        MainController mc = MainController.instance();
        mc.getHome().setVisible(true);
        mc.getHome().setLocationRelativeTo(this);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        MainController mc = MainController.instance();
        mc.getMenu().setVisible(true);
        mc.getMenu().setLocationRelativeTo(this);
        mc.getMenu().setPreviousInterface(this);
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddPurchase().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnAddLine;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDeleteLine;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableLines;
    private javax.swing.JTextField txtCost;
    private javax.swing.JTextField txtDescription;
    // End of variables declaration//GEN-END:variables
}
