/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

/**
 *
 * @author federicoponcedeleon
 */
public class BillInformationInterface extends javax.swing.JFrame {

    /**
     * Creates new form BillInformationInterface
     */
    public BillInformationInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelName = new javax.swing.JLabel();
        jLabelAmount = new javax.swing.JLabel();
        jLabelDate = new javax.swing.JLabel();
        jLabelReference = new javax.swing.JLabel();
        jButtonPay = new javax.swing.JButton();
        jButtonPaid = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        setMinimumSize(new java.awt.Dimension(310, 79));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(310, 91));
        setResizable(false);
        setSize(new java.awt.Dimension(310, 79));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelName.setText("Motivo");
        getContentPane().add(jLabelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 6, -1, -1));

        jLabelAmount.setText("Monto");
        getContentPane().add(jLabelAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 6, -1, -1));

        jLabelDate.setText("Fecha");
        getContentPane().add(jLabelDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 28, -1, -1));

        jLabelReference.setText("Referencia");
        getContentPane().add(jLabelReference, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 28, -1, -1));

        jButtonPay.setText("Pagar");
        jButtonPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPayActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 50, -1, -1));

        jButtonPaid.setText("Pago");
        getContentPane().add(jButtonPaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 50, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillInformationInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillInformationInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillInformationInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillInformationInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillInformationInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPaid;
    private javax.swing.JButton jButtonPay;
    private javax.swing.JLabel jLabelAmount;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelReference;
    // End of variables declaration//GEN-END:variables
}
