/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import Controllers.MainController;
import Controllers.UserController;
import Models.Friends;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author federicoponcedeleon
 */
public class FriendsInterface extends javax.swing.JFrame {

    /**
     * Creates new form FriendsInterface
     */
    public FriendsInterface() {
        initComponents();
    }
    
    ArrayList<Friends> list;
    
    public void listFriends() {
        MainController mc = MainController.instance();
        UserController uc = UserController.getInstanceUser();
        ArrayList<Friends> friends = uc.getFriends(mc.getCurrentUser().getUserName());
        this.list = friends;
        for (Friends friend : friends) {
            DefaultTableModel model = (DefaultTableModel) jTableFriends.getModel();
            model.addRow(new Object[]{friend.getUserId2()});
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFriends = new javax.swing.JTable();
        jButtonAdd = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(300, 480));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableFriends.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Usuario", "Nombre"
            }
        ));
        jTableFriends.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableFriendsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableFriends);
        if (jTableFriends.getColumnModel().getColumnCount() > 0) {
            jTableFriends.getColumnModel().getColumn(0).setResizable(false);
            jTableFriends.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 260, 290));

        jButtonAdd.setText("+");
        jButtonAdd.setToolTipText("Agregar amigo");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 40, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled.png"))); // NOI18N
        jLabel3.setToolTipText("Inicio");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, -10, 160, 90));

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu-icon.png"))); // NOI18N
        jLabel2.setToolTipText("");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, -10, 90, 60));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Amigos");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 120, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white-wallpaper.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 300, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        MainController.instance().getMenu().setVisible(true);
        MainController.instance().getMenu().setLocationRelativeTo(this);
        MainController.instance().getMenu().setPreviousInterface(this);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        MainController mc = MainController.instance();
        mc.getHome().setVisible(true);
        this.setVisible(false);
        this.dispose();
        mc.getHome().setLocationRelativeTo(this);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jTableFriendsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFriendsMouseClicked
        int row = jTableFriends.rowAtPoint(evt.getPoint());
        if (row >= 0) {
            Friends sFriend = this.list.get(row);
            UserController selectedFriend = UserController.getInstanceUser();
            UserInformation userFriend = new UserInformation();
            userFriend.setUser(selectedFriend.getUser(sFriend.getUserId2()));
            userFriend.setVisible(true);
            userFriend.showFriendInfo();
            this.setVisible(false);
            dispose();
        }
    }//GEN-LAST:event_jTableFriendsMouseClicked

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        AddFriend interf = new AddFriend();
        interf.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButtonAddActionPerformed

    public void friendsList(){
        int row = 1;
        MainController main = MainController.instance();
        UserController user = UserController.getInstanceUser();
        ArrayList<Friends> friends = user.getFriends(main.getCurrentUser().getUserName());
        for(int i=0; i<friends.size(); i++){
            Friends f = friends.get(i);
            if (f.getUserId1().equals(main.getCurrentUser().getUserName())){
                jTableFriends.setValueAt(f.getUserId2(), row, 1);
            }
            else{
                jTableFriends.setValueAt(f.getUserId2(), row, 1); 
            }
            row++;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FriendsInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FriendsInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FriendsInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FriendsInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FriendsInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFriends;
    // End of variables declaration//GEN-END:variables
}
