/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import Controllers.MainController;
import Controllers.MeetingController;
import Models.Meeting;
import Models.User;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JFrame;

/**
 *
 * @author federicoponcedeleon
 */
public class MeetingOptions extends javax.swing.JFrame {

    /**
     * Creates new form MeetingOptions
     */
    public MeetingOptions() {
        initComponents();
        jLabelMessage.setText("");
        loadMeetings();
        this.listOfMeetings = new ArrayList<>();
        jComboBoxMeetings.removeAllItems();
    }
    private JFrame previousInterface;
    private JFrame interfaceToLoadMeetingId; //should be add service or purchase interface only
    private ArrayList<Meeting> listOfMeetings;

    public void loadMeetings() {
        User currentUser = MainController.instance().getCurrentUser();
        if (currentUser == null) {
            jLabelMessage.setText("Ha ocurrido un error");
            jLabelMessage.setForeground(Color.red);
            return;
        }
        ArrayList<Meeting> list = MeetingController.instance().getAllOrganizedBy(currentUser.getUserName());
        if (list == null) {
            jLabelMessage.setText("Ha ocurrido un error");
            jLabelMessage.setForeground(Color.red);
            return;
        }
        if (list.isEmpty()) {
            jLabelMessage.setText("No se han encontrado reuniones organizadas");
            jLabelMessage.setForeground(Color.red);
            return;
        }
        for (Meeting meeting : list) {
            jComboBoxMeetings.addItem(meeting.getDescription());
        }
        this.listOfMeetings = list; 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxMeetings = new javax.swing.JComboBox<>();
        jButtonCancel = new javax.swing.JButton();
        jButtonConfirm = new javax.swing.JButton();
        jLabelMessage = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBoxMeetings.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBoxMeetings, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButtonCancel.setText("Cancelar");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        jButtonConfirm.setText("Aceptar");
        jButtonConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        jLabelMessage.setText("jLabel1");
        getContentPane().add(jLabelMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white-wallpaper.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmActionPerformed
        if (jComboBoxMeetings.getSelectedIndex() < 0) {
            jLabelMessage.setText("No ha seleccionado ninguna reunion");
            jLabelMessage.setForeground(Color.red);
            return;
        }
        Meeting selectedMeeting = this.listOfMeetings.get(jComboBoxMeetings.getSelectedIndex());
        //this.interfaceToLoadMeetingId.setMeeting(selectedMeeting); 
    }//GEN-LAST:event_jButtonConfirmActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        if (this.previousInterface != null) {
            this.previousInterface.setVisible(true);
        }
        this.dispose();
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MeetingOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MeetingOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MeetingOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MeetingOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MeetingOptions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonConfirm;
    private javax.swing.JComboBox<String> jComboBoxMeetings;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelMessage;
    // End of variables declaration//GEN-END:variables
}
