/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import Controllers.MainController;
import Controllers.MeetingController;
import Models.Bill;
import Models.Meeting;
import Models.User;
import java.awt.Color;
import java.util.ArrayList;

/**
 *
 * @author federicoponcedeleon
 */
public class MeetingInterface extends javax.swing.JFrame {

    /**
     * Creates new form MeetingInterface
     */
    public MeetingInterface() {
        initComponents();
        jLabelMessage.setText("");
    }
    
    private ArrayList<Meeting> list;
    
    
    public void setList(ArrayList<Meeting> list) {
        this.list = list;
    }

    public void listMeetings(int filter) {
        MainController mainC = MainController.instance();
        User currentUser = mainC.getCurrentUser();
        if (currentUser == null) {
            jLabelMessage.setText("Ha ocurrido un error");
            jLabelMessage.setForeground(Color.red);
            return;
        }
        MeetingController mc = MeetingController.instance();
        switch (filter) {
            case 0:
                this.list = mc.getAssisted(currentUser.getUserName());
                break;
            
            case 1: 
                this.list = mc.getDidntAssisted(currentUser.getUserName());
                break;
            
            case 2: 
                this.list = mc.getAllOrganizedBy(currentUser.getUserName());
                break;
                
            case 3: 
                this.list = mc.getAllMeetings(currentUser.getUserName());
                break;
        } 
        if (this.list == null) {
            jLabelMessage.setText("Ha ocurrido un error");
            jLabelMessage.setForeground(Color.red);
            return;
        }
        this.showMeetings();
    }
    
    public void showMeetings() {
        int i = 0;
        for (Meeting meeting : this.list) {
            jTableMeetings.setValueAt(meeting.getDate(), i, 0);
            jTableMeetings.setValueAt(meeting.getPlace(), i, 0);
            jTableMeetings.setValueAt(meeting.getDescription(), i, 0);
            jTableMeetings.setValueAt(meeting.getUsuOrgId(), i, 0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMeetings = new javax.swing.JTable();
        jLabelHome = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelMenu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabelMessage = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(300, 480));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableMeetings.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fecha", "Lugar", "Descripcion", "Organizador"
            }
        ));
        jTableMeetings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMeetingsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableMeetings);
        if (jTableMeetings.getColumnModel().getColumnCount() > 0) {
            jTableMeetings.getColumnModel().getColumn(0).setResizable(false);
            jTableMeetings.getColumnModel().getColumn(1).setResizable(false);
            jTableMeetings.getColumnModel().getColumn(2).setResizable(false);
            jTableMeetings.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 260, 300));

        jLabelHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled.png"))); // NOI18N
        jLabelHome.setToolTipText("Inicio");
        jLabelHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHomeMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, -10, 160, 90));

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu-icon.png"))); // NOI18N
        jLabelMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMenuMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, -10, 90, 60));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Reuniones");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 60));

        jButton1.setText("+");
        jButton1.setToolTipText("Agregar reunion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 40, 30));

        jLabelMessage.setText("jLabel2");
        getContentPane().add(jLabelMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white-wallpaper.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 300, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableMeetingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMeetingsMouseClicked
        int row = jTableMeetings.rowAtPoint(evt.getPoint());
            if (row >= 0) {
                Meeting selectedMeeting = this.list.get(row);
                MeetingInformationInterface interf = new MeetingInformationInterface();
                interf.setMeeting(selectedMeeting);
                interf.setVisible(true);
                this.setVisible(false);
                this.dispose();
            }
    }//GEN-LAST:event_jTableMeetingsMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AddMeetingInterface meetingInterf = new AddMeetingInterface();
        meetingInterf.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabelMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMenuMouseClicked
        MainController main = MainController.instance();
        main.getMenu().setVisible(true);
        main.getMenu().setPreviousInterface(this);
    }//GEN-LAST:event_jLabelMenuMouseClicked

    private void jLabelHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHomeMouseClicked
        MainController main = MainController.instance();
        main.getHome().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jLabelHomeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MeetingInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MeetingInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MeetingInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MeetingInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MeetingInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabelHome;
    private javax.swing.JLabel jLabelMenu;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMeetings;
    // End of variables declaration//GEN-END:variables
}
