/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import Controllers.MainController;
import Controllers.MeetingController;
import Models.Invited;
import Models.Meeting;
import Models.MeetingPurchase;
import Models.MeetingService;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author federicoponcedeleon
 */
public class MeetingInformationInterface extends javax.swing.JFrame {
    private Meeting meeting;
    private String friendId;                    
    /**
     * Creates new form MeetingInformationInterface
     */
    public MeetingInformationInterface() {
        initComponents();
        lblDate.setText(meeting.getDate().toString()); //CAMBIAR A DD/MM/YYYY
        lblOrganizer.setText(meeting.getUsuOrgId());
        lblPlace.setText(meeting.getPlace());
        lblTime.setText(meeting.getDate().toString()); //CAMBIAR A HH:MM
        fillInvitedTable();
        fillServiceTable();
        fillPurchaseTable();
        friendId = null;
    }
    
    public void setMeeting(Meeting meeting){
        this.meeting = meeting;
    }
    
    public void setFriendId(String friendId){
        this.friendId = friendId;        
    }
    
    public void fillServiceTable(){
        MeetingController mc = MeetingController.instance();
        ArrayList<MeetingService> serv = (mc.getMeetingServices(meeting.getMeetingId()));
        DefaultTableModel table = (DefaultTableModel) tblService.getModel();
        int i = 0;
        for (MeetingService service : serv) {
            tblService.setValueAt(service.getDescription(), i, 0);
            tblService.setValueAt(service.getServiceId(), i, 1);
            table.addRow(new Object[]{null});
            i++;
        }
    }
    
    public void isOrganizer(){
        MainController mainc = MainController.instance();
        if(!mainc.getCurrentUser().getUserName().equals(meeting.getUsuOrgId())){
            btnDelete.setText("Rechazar");
        }
    }
    
    public void fillPurchaseTable(){
        MeetingController mc = MeetingController.instance();
        ArrayList<MeetingPurchase> purch = (mc.getMeetingPurchases(meeting.getMeetingId()));
        DefaultTableModel table = (DefaultTableModel) tblPurchase.getModel();
        int i = 0;
        for (MeetingPurchase purchase : purch) {
            tblPurchase.setValueAt(purchase.getDescription(), i, 0);
            tblPurchase.setValueAt(purchase.getIdCompra(), i, 1);
            table.addRow(new Object[]{null});
            i++;
        }
    }
    
    public void fillInvitedTable(){
        MeetingController mc = MeetingController.instance();
        ArrayList<Invited> inv = (mc.getInvitedMeeting(meeting.getMeetingId()));
        DefaultTableModel table = (DefaultTableModel) tblInvites.getModel();
        int i = 0;
        for (Invited invited : inv) {
            tblInvites.setValueAt(invited.getUserId(), i, 0);
            table.addRow(new Object[]{null});
            i++;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDate = new javax.swing.JLabel();
        lblOrganizer = new javax.swing.JLabel();
        lblPlace = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnAddPurchase = new javax.swing.JToggleButton();
        btnAddService = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPurchase = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblService = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblInvites = new javax.swing.JTable();
        btnDeletePurchase = new javax.swing.JButton();
        btnDeleteService = new javax.swing.JButton();
        btnAddInvited = new javax.swing.JToggleButton();
        btnDeleteInvited = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnAccept = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(300, 480));
        setResizable(false);
        setSize(new java.awt.Dimension(300, 480));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDate.setText("Fecha");
        getContentPane().add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 60, 30));

        lblOrganizer.setText("Usu organizador");
        getContentPane().add(lblOrganizer, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, 30));

        lblPlace.setText("Lugar");
        getContentPane().add(lblPlace, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/miniService.png"))); // NOI18N
        jLabel5.setToolTipText("Servicios");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 80, 50));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled.png"))); // NOI18N
        jLabel11.setToolTipText("Inicio");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, -10, 160, 90));

        btnAddPurchase.setText("+");
        btnAddPurchase.setToolTipText("Agregar compra");
        btnAddPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPurchaseActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddPurchase, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 40, 30));

        btnAddService.setText("+");
        btnAddService.setToolTipText("Agregar servicio");
        btnAddService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddServiceActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddService, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 40, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/people-icon.png"))); // NOI18N
        jLabel6.setToolTipText("Invitados");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 210, 130, 60));

        lblTime.setText("Hora");
        getContentPane().add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, 30));

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu-icon.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, -10, 90, 60));

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Reunion");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 60));

        tblPurchase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null}
            },
            new String [] {
                "Descripcion"
            }
        ));
        jScrollPane1.setViewportView(tblPurchase);
        if (tblPurchase.getColumnModel().getColumnCount() > 0) {
            tblPurchase.getColumnModel().getColumn(0).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 100, 60));

        tblService.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null}
            },
            new String [] {
                "Descripcion"
            }
        ));
        jScrollPane2.setViewportView(tblService);
        if (tblService.getColumnModel().getColumnCount() > 0) {
            tblService.getColumnModel().getColumn(0).setResizable(false);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 100, 60));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MiniPurchase.png"))); // NOI18N
        jLabel8.setToolTipText("Compras");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 60, 40));

        tblInvites.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nombre"
            }
        ));
        jScrollPane3.setViewportView(tblInvites);
        if (tblInvites.getColumnModel().getColumnCount() > 0) {
            tblInvites.getColumnModel().getColumn(0).setResizable(false);
        }

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 170, 70));

        btnDeletePurchase.setText("-");
        btnDeletePurchase.setToolTipText("Eliminar compra");
        btnDeletePurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletePurchaseActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeletePurchase, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 40, 30));

        btnDeleteService.setText("-");
        btnDeleteService.setToolTipText("Eliminar servicio");
        btnDeleteService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteServiceActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeleteService, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, 40, 30));

        btnAddInvited.setText("+");
        btnAddInvited.setToolTipText("Agregar invitado");
        btnAddInvited.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddInvitedActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddInvited, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 40, 30));

        btnDeleteInvited.setText("-");
        btnDeleteInvited.setToolTipText("Eliminar invitado");
        btnDeleteInvited.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteInvitedActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeleteInvited, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 40, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calendar-icon.png"))); // NOI18N
        jLabel4.setToolTipText("Fecha");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 50, 120, 70));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/map-icon.png"))); // NOI18N
        jLabel12.setToolTipText("Lugar");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 80, 120, 80));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clock-icon.png"))); // NOI18N
        jLabel13.setToolTipText("Hora");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 120, 70));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/person-icon.png"))); // NOI18N
        jLabel14.setToolTipText("Organizador");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 140, 120, 70));

        btnAccept.setText("Aceptar");
        btnAccept.setToolTipText("Aceptar");
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });
        getContentPane().add(btnAccept, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 80, -1));

        btnDelete.setText("Eliminar");
        btnDelete.setToolTipText("Eliminar Reunion");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 80, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white-wallpaper.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 300, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddInvitedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddInvitedActionPerformed
        MainController mainc = MainController.instance();
        boolean bool = false;
        if (mainc.getCurrentUser().getUserName().equals(meeting.getUsuOrgId())){
            do{
                friendId = JOptionPane.showInputDialog("Ingrese el nombre de usuario de su amigo");
                MeetingController mc = MeetingController.instance();
                bool = mc.addInvitedToMeeting(friendId, meeting.getMeetingId());
            } while (!bool);
        }
    }//GEN-LAST:event_btnAddInvitedActionPerformed

    private void btnDeleteInvitedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteInvitedActionPerformed
        MainController mainc = MainController.instance();
        if (mainc.getCurrentUser().getUserName().equals(meeting.getUsuOrgId())){
            DefaultTableModel table = (DefaultTableModel) tblInvites.getModel();
            MeetingController mc = MeetingController.instance();
            int selectedRow = tblInvites.getSelectedRow();
            mc.deleteInvitedToMeeting(table.getValueAt(selectedRow, 0).toString(), meeting.getMeetingId());
            table.removeRow(selectedRow);
        }
    }//GEN-LAST:event_btnDeleteInvitedActionPerformed

    private void btnAddPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPurchaseActionPerformed
        MainController mainc = MainController.instance();
        if (mainc.getCurrentUser().getUserName().equals(meeting.getUsuOrgId())){
            AddPurchase purchInterface = new AddPurchase();
            purchInterface.setMeetingId(meeting.getMeetingId());
            purchInterface.show();
            purchInterface.setVisible(true);
            purchInterface.setLocationRelativeTo(this);
            dispose();
        }
    }//GEN-LAST:event_btnAddPurchaseActionPerformed

    private void btnDeletePurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletePurchaseActionPerformed
        MainController mainc = MainController.instance();
        if (mainc.getCurrentUser().getUserName().equals(meeting.getUsuOrgId())){
            PurchaseController pc = PurchaseController.instance();
            DefaultTableModel table = (DefaultTableModel) tblPurchase.getModel();
            int selectedRow = tblPurchase.getSelectedRow();
            pc.deleteMeetingPurchase(table.getValueAt(selectedRow, 1).toString());
            table.removeRow(selectedRow);
        }
    }//GEN-LAST:event_btnDeletePurchaseActionPerformed

    private void btnAddServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddServiceActionPerformed
        MainController mainc = MainController.instance();
        if (mainc.getCurrentUser().getUserName().equals(meeting.getUsuOrgId())){    
            AddServiceInterface servInterface = new AddServiceInterface();
            servInterface.setMeetingId(meeting.getMeetingId()); //service interface should get an id
            servInterface.setVisible(true);
            servInterface.setLocationRelativeTo(this);
            dispose();
        }
    }//GEN-LAST:event_btnAddServiceActionPerformed

    private void btnDeleteServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteServiceActionPerformed
        MainController mainc = MainController.instance();
        if (mainc.getCurrentUser().getUserName().equals(meeting.getUsuOrgId())){
            ServiceController pc = ServiceController.instance();
            DefaultTableModel table = (DefaultTableModel) tblService.getModel();
            int selectedRow = tblService.getSelectedRow();
            pc.deleteMeetingService(table.getValueAt(selectedRow, 1).toString());
            table.removeRow(selectedRow);
        }
    }//GEN-LAST:event_btnDeleteServiceActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        MainController mainc = MainController.instance();
        if (mainc.getCurrentUser().getUserName().equals(meeting.getUsuOrgId())){
            int option = JOptionPane.showConfirmDialog(null, "Seguro que desea eliminar la reunion?");
            if (option == 0){
                MeetingController mc = MeetingController.instance();
                mc.deleteMeeting(meeting.getMeetingId());
                MeetingInterface meetings = new MeetingInterface();
                ArrayList<Meeting> meetingArray = mc.getAllMeetings(mainc.getCurrentUser().getUserName());
                meetings.setList(meetingArray);
                meetings.setVisible(true);
                meetings.setLocationRelativeTo(this);
                dispose();
            }
        }
        else{
            int option = JOptionPane.showConfirmDialog(null, "Seguro que desea rechazar la invitacion a la reunion?");
            if (option == 0){
                MeetingController mc = MeetingController.instance();
                mc.rejectInivitation(mainc.getCurrentUser().getUserName(),meeting.getMeetingId());
                MeetingInterface meetings = new MeetingInterface();
                ArrayList<Meeting> meetingArray = mc.getAllMeetings(mainc.getCurrentUser().getUserName());
                meetings.setList(meetingArray);
                meetings.setVisible(true);
                meetings.setLocationRelativeTo(this);
                dispose();
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        MainController mc = MainController.instance();
        mc.getHome().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnAcceptActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        
    }//GEN-LAST:event_jLabel11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MeetingInformationInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MeetingInformationInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MeetingInformationInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MeetingInformationInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MeetingInformationInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JToggleButton btnAddInvited;
    private javax.swing.JToggleButton btnAddPurchase;
    private javax.swing.JToggleButton btnAddService;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDeleteInvited;
    private javax.swing.JButton btnDeletePurchase;
    private javax.swing.JButton btnDeleteService;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblOrganizer;
    private javax.swing.JLabel lblPlace;
    private javax.swing.JLabel lblTime;
    private javax.swing.JTable tblInvites;
    private javax.swing.JTable tblPurchase;
    private javax.swing.JTable tblService;
    // End of variables declaration//GEN-END:variables
}
