/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import Animacion.Animacion;
import Controllers.BillController;
import Controllers.MainController;
import Controllers.MeetingController;
import Controllers.PurchaseController;
import Models.Bill;
import Models.Meeting;
import Models.PersonalPurchase;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author federicoponcedeleon
 */
public class MenuInterface extends javax.swing.JFrame {

    /**
     * Creates new form MenuInterface
     */
    public MenuInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelPurchaseImg = new javax.swing.JLabel();
        jLabelMeetingImg = new javax.swing.JLabel();
        jLabelBillImg = new javax.swing.JLabel();
        jLabelFriendImg = new javax.swing.JLabel();
        jLabelPurchase = new javax.swing.JLabel();
        jLabelServiceImg = new javax.swing.JLabel();
        jLabelMeeting = new javax.swing.JLabel();
        jLabelFriends = new javax.swing.JLabel();
        jLabelBill = new javax.swing.JLabel();
        jLabelService = new javax.swing.JLabel();
        jLabelAddFriend = new javax.swing.JLabel();
        jLabelRemoveFriend = new javax.swing.JLabel();
        jLabelListFriends = new javax.swing.JLabel();
        jLabelListMeeting = new javax.swing.JLabel();
        jLabelAddMeeting = new javax.swing.JLabel();
        jLabelRemoveMeeting = new javax.swing.JLabel();
        jLabelListOrDeleteFriend = new javax.swing.JLabel();
        jLabelAddFriend2 = new javax.swing.JLabel();
        jLabelAddMeeting2 = new javax.swing.JLabel();
        jLabelListAllMeetings = new javax.swing.JLabel();
        jLabelListAssisted = new javax.swing.JLabel();
        jLabelListDidntAssisted = new javax.swing.JLabel();
        jLabelListOrganized = new javax.swing.JLabel();
        jLabelListOrDeletePurchase = new javax.swing.JLabel();
        jLabelAddPurchase2 = new javax.swing.JLabel();
        jLabelListOrDeleteService = new javax.swing.JLabel();
        jLabelAddService2 = new javax.swing.JLabel();
        jLabelListDidntCharged = new javax.swing.JLabel();
        jLabelAddBill2 = new javax.swing.JLabel();
        jLabelListPaidBills = new javax.swing.JLabel();
        jLabelListDidntPayBills = new javax.swing.JLabel();
        jLabelListAllBills = new javax.swing.JLabel();
        jLabelListCharged = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white-wallpaper.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 23, 260, 385));
        setMinimumSize(new java.awt.Dimension(260, 385));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(260, 385));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelPurchaseImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/purchase-icon.png"))); // NOI18N
        getContentPane().add(jLabelPurchaseImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 110, 90, 80));

        jLabelMeetingImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/meeting-icon.png"))); // NOI18N
        getContentPane().add(jLabelMeetingImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 20, -1, -1));

        jLabelBillImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bill-icon.png"))); // NOI18N
        getContentPane().add(jLabelBillImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 200, -1, -1));

        jLabelFriendImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/friends-icon.png"))); // NOI18N
        getContentPane().add(jLabelFriendImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -40, -1, -1));

        jLabelPurchase.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabelPurchase.setText("Compras");
        jLabelPurchase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPurchaseMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPurchase, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 110, 50));

        jLabelServiceImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/service-icon.png"))); // NOI18N
        getContentPane().add(jLabelServiceImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 150, -1, -1));

        jLabelMeeting.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabelMeeting.setText("Reuniones");
        jLabelMeeting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMeetingMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelMeeting, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 120, 50));

        jLabelFriends.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabelFriends.setText("Amigos");
        jLabelFriends.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelFriendsMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelFriends, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 100, 50));

        jLabelBill.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabelBill.setText("Gastos");
        jLabelBill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBillMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 100, 50));

        jLabelService.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabelService.setText("Servicios");
        jLabelService.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelServiceMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelService, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 120, 50));

        jLabelAddFriend.setText("Agregar ");
        getContentPane().add(jLabelAddFriend, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, -40, 190, -1));

        jLabelRemoveFriend.setText("Eliminar ");
        getContentPane().add(jLabelRemoveFriend, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, -40, 220, 40));

        jLabelListFriends.setText("Ver amigos");
        getContentPane().add(jLabelListFriends, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, -40, 180, -1));

        jLabelListMeeting.setText("Ver");
        getContentPane().add(jLabelListMeeting, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, -40, 100, -1));

        jLabelAddMeeting.setText("Agregar");
        getContentPane().add(jLabelAddMeeting, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, -40, 110, -1));

        jLabelRemoveMeeting.setText("Eliminar");
        getContentPane().add(jLabelRemoveMeeting, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, -40, 100, -1));

        jLabelListOrDeleteFriend.setText("Ver / Eliminar");
        getContentPane().add(jLabelListOrDeleteFriend, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, -40, -1, -1));

        jLabelAddFriend2.setText("Agregar ");
        getContentPane().add(jLabelAddFriend2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, -40, -1, -1));

        jLabelAddMeeting2.setText("Agregar");
        getContentPane().add(jLabelAddMeeting2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, -40, 190, -1));

        jLabelListAllMeetings.setText("Ver todas");
        getContentPane().add(jLabelListAllMeetings, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, -40, -1, -1));

        jLabelListAssisted.setText("Ver asistidas");
        getContentPane().add(jLabelListAssisted, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, -40, -1, -1));

        jLabelListDidntAssisted.setText("Ver no asistidas");
        getContentPane().add(jLabelListDidntAssisted, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, -40, -1, -1));

        jLabelListOrganized.setText("Ver organizadas");
        getContentPane().add(jLabelListOrganized, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, -40, -1, -1));

        jLabelListOrDeletePurchase.setText("Ver / Eliminar");
        getContentPane().add(jLabelListOrDeletePurchase, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, -40, -1, -1));

        jLabelAddPurchase2.setText("Agregar");
        getContentPane().add(jLabelAddPurchase2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, -40, 140, -1));

        jLabelListOrDeleteService.setText("Ver / Eliminar");
        getContentPane().add(jLabelListOrDeleteService, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, -40, -1, -1));

        jLabelAddService2.setText("Agregar");
        getContentPane().add(jLabelAddService2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, -40, 120, -1));

        jLabelListDidntCharged.setText("Ver no cobrados");
        getContentPane().add(jLabelListDidntCharged, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, -40, -1, -1));

        jLabelAddBill2.setText("Agregar");
        getContentPane().add(jLabelAddBill2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, -40, 160, -1));

        jLabelListPaidBills.setText("Ver pagos");
        getContentPane().add(jLabelListPaidBills, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, -40, -1, -1));

        jLabelListDidntPayBills.setText("Ver no pagos");
        getContentPane().add(jLabelListDidntPayBills, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, -40, -1, -1));

        jLabelListAllBills.setText("Ver todos");
        getContentPane().add(jLabelListAllBills, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, -40, -1, -1));

        jLabelListCharged.setText("Ver cobrados");
        getContentPane().add(jLabelListCharged, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, -40, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Ocultar");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 60, 120, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/person-icon.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, -20, 120, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 320, 435));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelFriendsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFriendsMouseClicked
        if (jLabelAddMeeting2.getY() > 0) this.closeMeeting();
        if (jLabelAddPurchase2.getY() > 0) this.closePurchase();
        if (jLabelAddService2.getY() > 0) this.closeService();
        if (jLabelAddBill2.getY() > 0) this.closeBill();
        if (jLabelAddFriend2.getY() < 0) {
            this.openFriends();
        } 
        else {
            this.closeFriends();
        }
    }//GEN-LAST:event_jLabelFriendsMouseClicked

    private void jLabelAddFriend2MouseClicked(java.awt.event.MouseEvent evt) {
        AddFriendInterface interf = new AddFriendInterface();
        this.setVisible(false);
        interf.setVisible(true);
        dispose();
    }
    
    private void jLabelListOrDeleteFriendMouseClicked(java.awt.event.MouseEvent evt) {
        ListFriendInterface interf = new ListFriendInterface();
        this.setVisible(false);
        interf.setVisible(true);
        dispose();
    }
    
    private void jLabelAddMeeting2MouseClicked(java.awt.event.MouseEvent evt) {
        AddReunionInterface interf = new AddReunionInterface();
        this.setVisible(false);
        interf.setVisible(true);
        dispose();
    }
    
    private void jLabelListAllMeetingsMouseClicked(java.awt.event.MouseEvent evt) {
        MeetingController meetingController = MeetingController.instance();
        MainController mainC = MainController.instance();
        ArrayList<Meeting> result = meetingController.
        ContainerListInterface interf = new ContainerListInterface();
        for (Bill bill : result) {
            BillInformationInterface billInterface = new BillInformationInterface();
            interf.addBill(billInterface);
        }
        this.setVisible(false);
        interf.setVisible(true);
        dispose();
    }
    
    private void jLabelAddBill2MouseClicked(java.awt.event.MouseEvent evt) {
        AddBillInterface interf = new AddBillInterface();
        this.setVisible(false);
        interf.setVisible(true);
        dispose();
    }
    
    private void jLabelListAllBillsMouseClicked(java.awt.event.MouseEvent evt) {
        BillController billController = BillController.instance();
        MainController mainC = MainController.instance();
        ArrayList<Bill> result = billController.getUsersBills(mainC.getCurrentUser().getUserName(), 0);
        ContainerListInterface interf = new ContainerListInterface();
        for (Bill bill : result) {
            BillInformationInterface billInterface = new BillInformationInterface();
            interf.addBill(billInterface);
        }
        this.setVisible(false);
        interf.setVisible(true);
        dispose();
    }
    
    private void jLabelListDidntAssistedMouseClicked(java.awt.event.MouseEvent evt) {
        ListDidntAssisted interf = new ListDidntAssisted();
        this.setVisible(false);
        interf.setVisible(true);
        dispose();
    }
    
    private void jLabelListDidntChargedMouseClicked(java.awt.event.MouseEvent evt) {
        BillController billController = BillController.instance();
        MainController mainC = MainController.instance();
        ArrayList<Bill> result = billController.getUsersBills(mainC.getCurrentUser().getUserName(), 4);
        ContainerListInterface interf = new ContainerListInterface();
        for (Bill bill : result) {
            BillInformationInterface billInterface = new BillInformationInterface();
            interf.addBill(billInterface);
        }
        this.setVisible(false);
        interf.setVisible(true);
        dispose();
    }
   
    private void jLabelListDidntPayBillsMouseClicked(java.awt.event.MouseEvent evt) {
        BillController billController = BillController.instance();
        MainController mainC = MainController.instance();
        ArrayList<Bill> result = billController.getUsersBills(mainC.getCurrentUser().getUserName(), 1);
        ContainerListInterface interf = new ContainerListInterface();
        for (Bill bill : result) {
            BillInformationInterface billInterface = new BillInformationInterface();
            interf.addBill(billInterface);
        }
        this.setVisible(false);
        interf.setVisible(true);
        dispose();
    }
    
    private void jLabelListPaidBillsMouseClicked(java.awt.event.MouseEvent evt) {
        BillController billController = BillController.instance();
        MainController mainC = MainController.instance();
        ArrayList<Bill> result = billController.getUsersBills(mainC.getCurrentUser().getUserName(), 2);
        ContainerListInterface interf = new ContainerListInterface();
        for (Bill bill : result) {
            BillInformationInterface billInterface = new BillInformationInterface();
            interf.addBill(billInterface);
        }
        this.setVisible(false);
        interf.setVisible(true);
        dispose();
    }
    
    private void jLabelListCharged(java.awt.event.MouseEvent evt) {
        /*BillController billController = BillController.instance();
        MainController mainC = MainController.instance();
        ArrayList<Bill> result = billController.getUsersBills(mainC.getCurrentUser().getUserName(), 3);
        ContainerListInterface interf = new ContainerListInterface();
        for (Bill bill : result) {
            BillInformationInterface billInterface = new BillInformationInterface();
            interf.addBill(billInterface);
        }*/
        MainController mc = MainController.instance();
        ArrayList<JFrame> list = new ArrayList<>();
        BillInformationInterface billInterface = new BillInformationInterface();
        list.add(billInterface);
        billInterface = new BillInformationInterface();
        list.add(billInterface);
        billInterface = new BillInformationInterface();
        list.add(billInterface);
        mc.showContent(list);
        this.setVisible(false);
        dispose();
    }
    
    private void jLabelListOrDeletePurchaseMouseClicked(java.awt.event.MouseEvent evt) {
        PurchaseController purchaseC = PurchaseController.instance();
        MainController mainC = MainController.instance();
        ArrayList<PersonalPurchase> purchases = purchaseC.getAllPersonalPurchase(mainC.getCurrentUser().getUserName());
        ContainerListInterface interf = new ContainerListInterface();
        for (PersonalPurchase purchase : purchases) {
            PurchaseInformationInterface purchaseInfo = new PurchaseInformationInterface(purchase);
            interf.addPurchase(purchaseInfo);
        }
        this.setVisible(false);
        interf.setVisible(true);
        dispose();
    }
    
    private void jLabelAddPurchase2MouseClicked(java.awt.event.MouseEvent evt) {
        AddBillInterface interf = new AddBillInterface();
        this.setVisible(false);
        interf.setVisible(true);
        dispose();
    }
    
    private void jLabelListOrDeleteServiceMouseClicked(java.awt.event.MouseEvent evt) {
        ListOrDeleteService interf = new ListOrDeleteService();
        this.setVisible(false);
        interf.setVisible(true);
        dispose();
    }
    
    private void jLabelAddService2MouseClicked(java.awt.event.MouseEvent evt) {
        AddServiceInterface interf = new AddServiceInterface();
        this.setVisible(false);
        interf.setVisible(true);
        dispose();
    }
    
    
    private void openFriends() {
        Animacion.bajar(-40, 51, 4, 2, jLabelAddFriend2);
        Animacion.bajar(-40, 72, 4, 2, jLabelListOrDeleteFriend);
        Animacion.bajar(60, 90, 4, 2, jLabelMeeting);
        Animacion.bajar(20, 48, 6, 2, jLabelMeetingImg);
        Animacion.bajar(120, 160, 4, 2, jLabelPurchase);
        Animacion.bajar(110, 148, 6, 2, jLabelPurchaseImg);
        Animacion.bajar(180, 220, 4, 2, jLabelService);
        Animacion.bajar(150, 178, 6, 2, jLabelServiceImg);
        Animacion.bajar(240, 280, 4, 2, jLabelBill);
        Animacion.bajar(200, 238, 6, 2, jLabelBillImg);
    }
    
    private void closeFriends() {
        Animacion.subir(jLabelAddFriend.getY(), -40, 4, 2, jLabelAddFriend2);
        Animacion.subir(jLabelListFriends.getY(), -40, 4, 2, jLabelListOrDeleteFriend);
        Animacion.subir(jLabelMeeting.getY(), 60, 4, 2, jLabelMeeting);
        Animacion.subir(jLabelMeetingImg.getY(), 20, 6, 2, jLabelMeetingImg);
        Animacion.subir(jLabelPurchase.getY(), 120, 4, 2, jLabelPurchase);
        Animacion.subir(jLabelPurchaseImg.getY(), 110, 6, 2, jLabelPurchaseImg);
        Animacion.subir(jLabelService.getY(), 180, 4, 2, jLabelService);
        Animacion.subir(jLabelServiceImg.getY(), 150, 6, 2, jLabelServiceImg);
        Animacion.subir(jLabelBill.getY(), 240, 4, 2, jLabelBill);
        Animacion.subir(jLabelBillImg.getY(), 200, 6, 2, jLabelBillImg);
    }
    
    private void jLabelMeetingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMeetingMouseClicked
        if (jLabelAddFriend2.getY() > 0) this.closeFriends();
        if (jLabelAddPurchase2.getY() > 0) this.closePurchase();
        if (jLabelAddService2.getY() > 0) this.closeService();
        if (jLabelAddBill2.getY() > 0) this.closeBill();
        if (jLabelAddMeeting2.getY() < 0) {
            this.openMeeting();
        } 
        else {
            this.closeMeeting();
        }
        
    }//GEN-LAST:event_jLabelMeetingMouseClicked

    private void jLabelPurchaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPurchaseMouseClicked
        if (jLabelAddFriend2.getY() > 0) this.closeFriends();
        if (jLabelAddMeeting2.getY() > 0) this.closeMeeting();
        if (jLabelAddService2.getY() > 0) this.closeService();
        if (jLabelAddBill2.getY() > 0) this.closeBill();
        if (jLabelAddPurchase2.getY() < 0) {
            this.openPurchase();
        }
        else {
            this.closePurchase();
        }
    }//GEN-LAST:event_jLabelPurchaseMouseClicked

    private void jLabelServiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelServiceMouseClicked
        if (jLabelAddFriend2.getY() > 0) this.closeFriends();
        if (jLabelAddMeeting2.getY() > 0) this.closeMeeting();
        if (jLabelAddPurchase2.getY() > 0) this.closePurchase();
        if (jLabelAddBill2.getY() > 0) this.closeBill();
        if (jLabelAddService2.getY() < 0) {
            this.openService();
        }
        else {
            this.closeService();
        }
    }//GEN-LAST:event_jLabelServiceMouseClicked

    private void jLabelBillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBillMouseClicked
        if (jLabelAddFriend2.getY() > 0) this.closeFriends();
        if (jLabelAddMeeting2.getY() > 0) this.closeMeeting();
        if (jLabelAddPurchase2.getY() > 0) this.closePurchase();
        if (jLabelAddService2.getY() > 0) this.closeService();
        if (jLabelAddBill2.getY() < 0) {
            this.openBill();
        }
        else {
            this.closeBill();
        }
    }//GEN-LAST:event_jLabelBillMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void openBill(){
        Animacion.bajar(-40, 280, 4, 2, jLabelAddBill2);
        Animacion.bajar(-40, 302, 4, 2, jLabelListPaidBills);
        Animacion.bajar(-40, 324, 4, 2, jLabelListDidntPayBills);
        Animacion.bajar(-40, 346, 4, 2, jLabelListCharged);
        Animacion.bajar(-40, 368, 4, 2, jLabelListDidntCharged);
        Animacion.bajar(-40, 390, 4, 2, jLabelListAllBills);
        
    }
    
    private void closeBill() {
        Animacion.subir(jLabelAddBill2.getY(), -40, 4, 2, jLabelAddBill2);
        Animacion.subir(jLabelListPaidBills.getY(), -40, 4, 2, jLabelListPaidBills);
        Animacion.subir(jLabelListDidntPayBills.getY(), -40, 4, 2, jLabelListDidntPayBills);
        Animacion.subir(jLabelListCharged.getY(), -40, 4, 2, jLabelListCharged);
        Animacion.subir(jLabelListDidntCharged.getY(), -40, 4, 2, jLabelListDidntCharged);
        Animacion.subir(jLabelListAllBills.getY(), -40, 4, 2, jLabelListAllBills);
    }
    
    private void openService() {
        Animacion.bajar(-40, 220, 4, 2, jLabelAddService2);
        Animacion.bajar(-40, 241, 4, 2, jLabelListOrDeleteService);
        Animacion.bajar(240, 260, 4, 2, jLabelBill);
        Animacion.bajar(200, 218, 6, 2, jLabelBillImg);
    }
    
    private void closeService() {
        Animacion.subir(jLabelAddService2.getY(), -40, 4, 2, jLabelAddService2);
        Animacion.subir(jLabelBill.getY(), -40, 4, 2, jLabelListOrDeleteService);
        Animacion.subir(jLabelBill.getY(), 240, 4, 2, jLabelBill);
        Animacion.subir(jLabelBillImg.getY(), 200, 6, 2, jLabelBillImg);
    }
    
    private void openPurchase() {
        
        Animacion.bajar(-40, 160, 4, 2, jLabelAddPurchase2);
        Animacion.bajar(-40, 183, 4, 2, jLabelListOrDeletePurchase);
        Animacion.bajar(180, 210, 4, 2, jLabelService);
        Animacion.bajar(150, 178, 6, 2, jLabelServiceImg);
        Animacion.bajar(240, 280, 4, 2, jLabelBill);
        Animacion.bajar(200, 238, 6, 2, jLabelBillImg);
        
        
        
    }
    
    private void closePurchase() {
        Animacion.subir(jLabelAddPurchase2.getY(), -40, 4, 2, jLabelAddPurchase2);
        Animacion.subir(jLabelListOrDeletePurchase.getY(), -40, 4, 2, jLabelListOrDeletePurchase);
        Animacion.subir(jLabelService.getY(), 180, 4, 2, jLabelService);
        Animacion.subir(jLabelServiceImg.getY(), 150, 6, 2, jLabelServiceImg);
        Animacion.subir(jLabelBill.getY(), 240, 4, 2, jLabelBill);
        Animacion.subir(jLabelBillImg.getY(), 200, 6, 2, jLabelBillImg);
    }
    
    private void openMeeting() {
        Animacion.bajar(-40, 100, 4, 2, jLabelAddMeeting2); //105
        Animacion.bajar(-40, 121, 4, 2, jLabelListAssisted); //126
        Animacion.bajar(-40, 142, 4, 2, jLabelListDidntAssisted); //147
        Animacion.bajar(-40, 163, 4, 2, jLabelListOrganized); //147
        Animacion.bajar(-40, 184, 4, 2, jLabelListAllMeetings); //147
        Animacion.bajar(jLabelPurchase.getY(), 200, 4, 2, jLabelPurchase);
        Animacion.bajar(jLabelPurchaseImg.getY(), 180, 6, 2, jLabelPurchaseImg);
        Animacion.bajar(jLabelService.getY(), 250, 4, 2, jLabelService);
        Animacion.bajar(jLabelServiceImg.getY(), 210, 6, 2, jLabelServiceImg);
        Animacion.bajar(jLabelBill.getY(), 310, 4, 2, jLabelBill);
        Animacion.bajar(jLabelBillImg.getY(), 260, 6, 2, jLabelBillImg);
    }
    
    private void closeMeeting() {
        Animacion.subir(jLabelAddMeeting2.getY(), -40, 4, 2, jLabelAddMeeting2);
        Animacion.subir(jLabelListAssisted.getY(), -40, 4, 2, jLabelListAssisted); //126
        Animacion.subir(jLabelListDidntAssisted.getY(), -40, 4, 2, jLabelListDidntAssisted); //147
        Animacion.subir(jLabelListOrganized.getY(), -40, 4, 2, jLabelListOrganized); //147
        Animacion.subir(jLabelListAllMeetings.getY(), -40, 4, 2, jLabelListAllMeetings); //147
        Animacion.subir(jLabelPurchase.getY(), 120, 4, 2, jLabelPurchase);
        Animacion.subir(jLabelPurchaseImg.getY(), 110, 6, 2, jLabelPurchaseImg);
        Animacion.subir(jLabelService.getY(), 180, 4, 2, jLabelService);
        Animacion.subir(jLabelServiceImg.getY(), 150, 6, 2, jLabelServiceImg);
        Animacion.subir(jLabelBill.getY(), 240, 4, 2, jLabelBill);
        Animacion.subir(jLabelBillImg.getY(), 200, 6, 2, jLabelBillImg);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelAddBill2;
    private javax.swing.JLabel jLabelAddFriend;
    private javax.swing.JLabel jLabelAddFriend2;
    private javax.swing.JLabel jLabelAddMeeting;
    private javax.swing.JLabel jLabelAddMeeting2;
    private javax.swing.JLabel jLabelAddPurchase2;
    private javax.swing.JLabel jLabelAddService2;
    private javax.swing.JLabel jLabelBill;
    private javax.swing.JLabel jLabelBillImg;
    private javax.swing.JLabel jLabelFriendImg;
    private javax.swing.JLabel jLabelFriends;
    private javax.swing.JLabel jLabelListAllBills;
    private javax.swing.JLabel jLabelListAllMeetings;
    private javax.swing.JLabel jLabelListAssisted;
    private javax.swing.JLabel jLabelListCharged;
    private javax.swing.JLabel jLabelListDidntAssisted;
    private javax.swing.JLabel jLabelListDidntCharged;
    private javax.swing.JLabel jLabelListDidntPayBills;
    private javax.swing.JLabel jLabelListFriends;
    private javax.swing.JLabel jLabelListMeeting;
    private javax.swing.JLabel jLabelListOrDeleteFriend;
    private javax.swing.JLabel jLabelListOrDeletePurchase;
    private javax.swing.JLabel jLabelListOrDeleteService;
    private javax.swing.JLabel jLabelListOrganized;
    private javax.swing.JLabel jLabelListPaidBills;
    private javax.swing.JLabel jLabelMeeting;
    private javax.swing.JLabel jLabelMeetingImg;
    private javax.swing.JLabel jLabelPurchase;
    private javax.swing.JLabel jLabelPurchaseImg;
    private javax.swing.JLabel jLabelRemoveFriend;
    private javax.swing.JLabel jLabelRemoveMeeting;
    private javax.swing.JLabel jLabelService;
    private javax.swing.JLabel jLabelServiceImg;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
