/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import apple.laf.JRSUIConstants;
import javafx.animation.Animation;

/**
 *
 * @author federicoponcedeleon
 */
public class MenuInterface extends javax.swing.JFrame {

    /**
     * Creates new form MenuInterface
     */
    public MenuInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelPurchase = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelMeeting = new javax.swing.JLabel();
        jLabelFriends = new javax.swing.JLabel();
        jLabelBill = new javax.swing.JLabel();
        jLabelService = new javax.swing.JLabel();
        jLabelAddFriend = new javax.swing.JLabel();
        jLabelRemoveFriend = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white-wallpaper.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(300, 480));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/purchase-icon.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 110, 90, 80));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/meeting-icon.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 20, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bill-icon.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 200, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/friends-icon.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -40, -1, -1));

        jLabelPurchase.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabelPurchase.setText("Compras");
        getContentPane().add(jLabelPurchase, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 110, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/service-icon.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 150, -1, -1));

        jLabelMeeting.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabelMeeting.setText("Reuniones");
        getContentPane().add(jLabelMeeting, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 120, 50));

        jLabelFriends.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabelFriends.setText("Amigos");
        jLabelFriends.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelFriendsMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelFriends, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 100, 50));

        jLabelBill.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabelBill.setText("Gastos");
        getContentPane().add(jLabelBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 100, 50));

        jLabelService.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabelService.setText("Servicios");
        getContentPane().add(jLabelService, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 120, 50));

        jLabelAddFriend.setText("Agregar ");
        getContentPane().add(jLabelAddFriend, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 190, -1));

        jLabelRemoveFriend.setText("Eliminar ");
        getContentPane().add(jLabelRemoveFriend, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 220, 40));
        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 290, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelFriendsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFriendsMouseClicked
        Animacion animacion = new Animacion();
        animacion.bajar(100,40,1, jLabelRemoveFriend);
        animacion.bajar(100,70,1, jLabelAddFriend);
    }//GEN-LAST:event_jLabelFriendsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelAddFriend;
    private javax.swing.JLabel jLabelBill;
    private javax.swing.JLabel jLabelFriends;
    private javax.swing.JLabel jLabelMeeting;
    private javax.swing.JLabel jLabelPurchase;
    private javax.swing.JLabel jLabelRemoveFriend;
    private javax.swing.JLabel jLabelService;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
