/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import Controllers.MainController;
import Controllers.PurchaseController;
import Models.Bill;
import Models.IPurchase;
import Models.MeetingPurchase;
import Models.PersonalPurchase;
import Models.User;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author federicoponcedeleon
 */
public class PurchaseInterface extends javax.swing.JFrame {
    /**
     * Creates new form PurchaseInterface
     */
    public PurchaseInterface() {
        initComponents();
        jLabelMessage.setText("");
        this.meetingId = null;
    }
    private String meetingId;
    private ArrayList<IPurchase> toShow;

    public void showPurchases() throws SQLException {
        PurchaseController pc = PurchaseController.instance();
        ArrayList<IPurchase> list;
        if (this.meetingId == null) { //need to list personal purchases
            
            list = pc.getAllPersonalPurchase(MainController.instance().getCurrentUser().getUserName());
            
        }
        else {
            list = pc.getAllMeetingPurchase(this.meetingId);
            
        }
        if (list == null) {
                jLabelMessage.setText("Ha ocurrido un error al obtener las compras");
                jLabelMessage.setForeground(Color.red);
                return;
            }
        this.toShow = list;
        for (int i = 0; i < list.size(); i++) {
            DefaultTableModel table = (DefaultTableModel) jTablePurchases.getModel();
            table.addRow(new Object[]{list.get(i).getDescription()});
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePurchases = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonAdd = new javax.swing.JButton();
        jLabelMessage = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(300, 480));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTablePurchases.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descripcion"
            }
        ));
        jTablePurchases.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePurchasesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePurchases);
        if (jTablePurchases.getColumnModel().getColumnCount() > 0) {
            jTablePurchases.getColumnModel().getColumn(0).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 270, 300));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled.png"))); // NOI18N
        jLabel12.setToolTipText("Inicio");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, -10, 160, 90));

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu-icon.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, -10, 90, 60));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Compras");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 60));

        jButtonAdd.setText("+");
        jButtonAdd.setToolTipText("Nueva Compra");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 40, 30));

        jLabelMessage.setText("jLabel2");
        getContentPane().add(jLabelMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white-wallpaper.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 310, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        if (this.toShow.get(0).isPersonalPurchase()) {
            AddPurchase interf = new AddPurchase();
            interf.setVisible(true);
            interf.setLocationRelativeTo(this);
            this.setVisible(false);
            this.dispose();
        }
        else { //tengo que validar que el que va a agregar la compra sea el organizador de la reunion
            User currentUser = MainController.instance().getCurrentUser();
            if (currentUser == null) {
                jLabelMessage.setText("Ha ocurrido un error");
                jLabelMessage.setForeground(Color.red);
                return;
            }
            else {
                if (this.toShow.get(0).getReferenceId().equals(currentUser.getUserName())) {
                    AddPurchase interf = new AddPurchase();
                    interf.setMeetingId(this.toShow.get(0).getReferenceId());
                    interf.setVisible(true);
                    interf.setLocationRelativeTo(this);
                    this.setVisible(false);
                    this.dispose();
                }
            }
        }
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        MainController.instance().getMenu().setVisible(true);
        MainController.instance().getMenu().setLocationRelativeTo(this);
        MainController.instance().getMenu().setPreviousInterface(this);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        MainController mc = MainController.instance();
        mc.getHome().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jTablePurchasesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePurchasesMouseClicked
        int row = jTablePurchases.rowAtPoint(evt.getPoint());
        if (row >= 0) {
            IPurchase selectedPurchase = this.toShow.get(row);
            PurchaseInformationInterface interf = new PurchaseInformationInterface();
            interf.setPurchase(selectedPurchase);
            interf.showPurchase();
            interf.setVisible(true);
            this.setVisible(false);
            dispose();
        }
    }//GEN-LAST:event_jTablePurchasesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PurchaseInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PurchaseInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PurchaseInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PurchaseInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PurchaseInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePurchases;
    // End of variables declaration//GEN-END:variables
}
