/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import Controllers.MainController;
import Controllers.ServiceController;
import Models.MeetingService;
import Models.PersonalService;
import java.awt.Color;

/**
 *
 * @author federicoponcedeleon
 */
public class ServiceInformationInterface extends javax.swing.JFrame {

    /**
     * Creates new form ServiceInformationInterface
     */
    public ServiceInformationInterface() {
        initComponents();
    }
    
    private PersonalService personal;
    private MeetingService meeting;

    public PersonalService getPersonal() {
        return personal;
    }

    public void setPersonal(PersonalService personal) {
        this.personal = personal;
        this.meeting = null;
    }

    public MeetingService getMeeting() {
        return meeting;
    }

    public void setMeeting(MeetingService meeting) {
        this.meeting = meeting;
        this.personal = null;
    }
    
    public void show() {
        if (this.personal != null) {
            jLabelCompany.setText(this.personal.getCompany());
            jLabelCompany.setVisible(true);
            jLabelNameService.setText(this.personal.getName());
            jLabelNameService.setVisible(true);
            jLabelDate.setText(this.personal.getDate().toString());
            jLabelDate.setVisible(true);
            jLabelDescription.setText(this.personal.getDescription());
            jLabelDescription.setVisible(true);
        }
        else if (this.meeting != null) {
            jLabelCompany.setText(this.meeting.getCompany());
            jLabelCompany.setVisible(true);
            jLabelNameService.setText(this.meeting.getName());
            jLabelNameService.setVisible(true);
            jLabelDate.setVisible(false);
            jLabelDescription.setText(this.meeting.getDescription());
            jLabelDescription.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelNameService = new javax.swing.JLabel();
        jLabelCompany = new javax.swing.JLabel();
        jLabelDescription = new javax.swing.JLabel();
        jLabelDate = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButtonAccept = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jLabelMessage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu-icon.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 90, 60));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(300, 480));
        setResizable(false);
        setSize(new java.awt.Dimension(300, 480));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled.png"))); // NOI18N
        jLabel12.setToolTipText("Inicio");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, -10, 160, 90));

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu-icon.png"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, -10, 90, 60));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Servicio");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 140, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 60));

        jLabelNameService.setText("Nombre");
        jLabelNameService.setToolTipText("Nombre del servicio");
        getContentPane().add(jLabelNameService, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        jLabelCompany.setText("Empresa");
        getContentPane().add(jLabelCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        jLabelDescription.setText("Descripcion");
        getContentPane().add(jLabelDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, 30));

        jLabelDate.setText("Fecha");
        getContentPane().add(jLabelDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/miniService.png"))); // NOI18N
        jLabel7.setToolTipText("Nombre");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/description-icon.png"))); // NOI18N
        jLabel8.setToolTipText("Descripcion");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 110, 60));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empresa-icono-png.png"))); // NOI18N
        jLabel14.setToolTipText("Empresa");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 60, 50));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calendar-icon.png"))); // NOI18N
        jLabel13.setToolTipText("Fecha");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 220, 140, 70));

        jButtonAccept.setText("Aceptar");
        jButtonAccept.setToolTipText("Aceptar");
        jButtonAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcceptActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAccept, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 80, -1));

        jButtonDelete.setText("Eliminar");
        jButtonDelete.setToolTipText("Eliminar servicio");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 80, -1));

        jLabelMessage.setText("Esto se cambiara");
        getContentPane().add(jLabelMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white-wallpaper.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 300, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcceptActionPerformed
        MainController.instance().getHome().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButtonAcceptActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        ServiceController serviceC = ServiceController.instance();
        boolean success = false;
        if (this.personal != null) {
            success = serviceC.deletePersonalService(this.personal.getServiceId());
            
        }
        else if (this.meeting != null) {
            success = serviceC.deleteMeetingService(this.meeting.getServiceId());
        }
        
        if (success) {
            jLabelMessage.setText("Eliminado correctamente");
            jLabelMessage.setForeground(Color.GREEN);
        }
        else {
            jLabelMessage.setText("Ocurrio un error al eliminar el servicio");
            jLabelMessage.setForeground(Color.red);
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServiceInformationInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServiceInformationInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServiceInformationInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServiceInformationInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServiceInformationInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAccept;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCompany;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelDescription;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JLabel jLabelNameService;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
